[16.0][ADD] new module project_customer_access
akretion/support pull request #63
Opened 2024-12-09 16:23 UTC by clementmbr

WIP

2024-12-24 18:07 UTC, clementmbr commented
@sebastienbeau @Kev-Roche  my project_customer_access is ready for review!

I just have a doubt about 2 things :
- I didn't find any modules displaying the `cross_connect_client_id` field on res.users form view, so I added it [here](https://github.com/akretion/support/pull/63/files#diff-ffed9170c0652b8017245e5fdb88b7fee34c449cd06b7f3819ae38bf2e7e983bR305) for testing purposes through the UI... I understand it could be much better to put it in another module, but where?

- There is this strange non-obvious behavior with the UI when you want to create a user in a security group based on the "Backend User" group : as the "Backend User" group is from the "User  Type" category, the UI doesn't display other categories if this first group is selected.
The workaround is to add the user to the group through the group itself as I explained in the [Readme](https://github.com/akretion/support/pull/63/files#diff-e152db41c2b0d3d2cc55dd5cdcdea7ca81cb31cfa92adf5797b61b8a29841042R20). Let me know if it needs to be improved (if it's really needed to create these kind of customer users through the UI).

Thanks!

2024-12-24 18:17 UTC, clementmbr commented
@sebastienbeau my project_customer_access is ready for review!

I just have a doubt about 2 things :
- I didn't find any modules displaying the `cross_connect_client_id` field on res.users form view, so I added it here for testing purposes through the UI... but I understand it could be much better to put it in another module.
-

2025-01-23 14:29 UTC, sebastienbeau requested changes

2025-01-23 14:29 UTC, sebastienbeau commented on project_customer_access/data/project_customer_access_demo.xml
> +            <field name="api_key">server-api-key</field>
TODO move this in directory demo

2025-01-23 14:29 UTC, sebastienbeau commented on project_customer_access/data/res_groups.xml
> +    </record>
Move this in directory security

2026-03-06 13:25 UTC, florian-dacosta commented
Closed in favor of https://github.com/akretion/support/pull/74

2026-03-06 13:25 UTC, closed without merging